const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
const source=fs.readFileSync(require.resolve('../../js/analytics.js'),'utf8');const P=require('../../js/personalization.js');const I=require('../../js/job-identity.js');
function storage(values={}){return {values,getItem:k=>values[k]??null,setItem:(k,v)=>{values[k]=v;},removeItem:k=>{delete values[k];}};}
function harness(local=storage(),session=storage(),responses=[]){
 const wl={},dl={},intervals=[],requests=[];let now=1000000,signed=false;
 const window={crypto:crypto.webcrypto,SUJobIdentity:I,SUPersonalization:P,SUAuth:{signedIn:()=>signed,getToken:async()=>{if(!signed)throw Error();return 'synthetic';}},addEventListener:(n,f)=>{(wl[n]||=[]).push(f);},dispatchEvent:e=>(wl[e.type]||[]).forEach(f=>f(e))};
 const document={readyState:'loading',hidden:false,addEventListener:(n,f)=>{(dl[n]||=[]).push(f);}};
 vm.runInNewContext(source,{window,document,navigator:{globalPrivacyControl:false},localStorage:local,sessionStorage:session,location:{pathname:'/jobs.html'},setInterval:(f)=>intervals.push(f),Date:class extends Date{static now(){return now;}},CustomEvent:class{constructor(type,init={}){this.type=type;this.detail=init.detail;}},TextEncoder,Uint8Array,fetch:async(url,options)=>{requests.push({url,options});const response=responses.length?responses.shift():{ok:true,status:200};return {...response,json:async()=>({jobs:{}})};}});
 return {api:window.SUAnalytics,requests,local,session,window,document,intervals,tick:n=>{now+=n;intervals.forEach(f=>f());},start:()=>dl.DOMContentLoaded.forEach(f=>f()),auth:(value,changed=false)=>{signed=value;window.dispatchEvent({type:'su:auth-changed',detail:{signedIn:value,accountChanged:changed}});},consent:()=>window.dispatchEvent({type:'su:consent-changed'}),visibility:hidden=>{document.hidden=hidden;dl.visibilitychange.forEach(f=>f());}};
}
test('before consent no IDs, requests, queued events or pre-choice active time',async()=>{const h=harness();h.start();h.tick(30000);await h.api.flush();assert.equal(h.requests.length,0);assert.deepEqual(h.local.values,{});h.local.setItem('su_consent_v3','granted');h.consent();await h.api.flush();const events=h.requests.flatMap(r=>JSON.parse(r.options.body||'{"events":[]}').events||[]);assert.ok(events.some(e=>e.name==='page_view'));assert.equal(events.filter(e=>e.name==='page_engagement').length,0);});
test('same-account initial Firebase resolution preserves session across pages, transition rotates',async()=>{const local=storage({su_consent_v3:'granted'}),session=storage();let a=harness(local,session);a.auth(true,false);await a.api.flush();const first=JSON.parse(a.requests.find(r=>r.options.body).options.body).session;let b=harness(local,session);b.auth(true,false);await b.api.flush();assert.equal(JSON.parse(b.requests.find(r=>r.options.body).options.body).session,first);b.auth(false,true);await b.api.flush();assert.notEqual(JSON.parse(b.requests.at(-1).options.body).session,first);});
test('detail exploration recorded without Apply, aliases deduplicated and no text leaked',async()=>{const h=harness(storage({su_consent_v3:'granted'}));const job={link:'https://jobs.lever.co/acme/11111111-2222-3333-4444-555555555555',ind:'Social',role:'Role',co:'Company'};await h.api.registerJobs([job]);h.api.job('job_open',job.link+'?utm_source=example');h.api.job('job_open',job.link);h.api.emit('search_used', {query:'secret@example.invalid',notes:'private'});await h.api.flush();const text=h.requests[0].options.body;const body=JSON.parse(text);assert.equal(body.events.filter(e=>e.name==='job_open').length,1);assert.equal(body.events.filter(e=>e.name==='apply_click').length,0);assert.doesNotMatch(text,/secret|private|lever.co/);});
test('visible feedback popup does not produce away duration; observed return caps15min',async()=>{const h=harness(storage({su_consent_v3:'granted'}));const job={link:'https://example.com/job/1',ind:'Social'};await h.api.registerJobs([job]);h.api.job('apply_click',job.link);h.tick(240000);await h.api.flush();let events=h.requests.flatMap(r=>JSON.parse(r.options.body||'{"events":[]}').events||[]);assert.equal(events.filter(e=>e.name==='outbound_return').length,0);h.api.job('apply_click',job.link);h.visibility(true);h.tick(1200000);h.visibility(false);await h.api.flush();await h.api.flush();events=h.requests.flatMap(r=>JSON.parse(r.options.body||'{"events":[]}').events||[]);const away=events.find(e=>e.name==='outbound_return');assert.equal(away.seconds,900);assert.equal(away.capped,true);});

test('permanent4xxbatches are discarded so later valid events continue;429and5xxretry',async()=>{
  for(const status of [400,401,403,404,413]){
    const h=harness(storage({su_consent_v3:'granted'}),storage(),[{ok:false,status},{ok:true,status:200}]);
    h.api.emit('search_used',{});await h.api.flush();h.api.emit('theme_change',{theme:'original'});await h.api.flush();
    assert.equal(h.requests.length,2);const second=JSON.parse(h.requests[1].options.body);assert.equal(second.events.length,1);assert.equal(second.events[0].name,'theme_change');
  }
  for(const status of [429,500,503]){
    const h=harness(storage({su_consent_v3:'granted'}),storage(),[{ok:false,status},{ok:true,status:200}]);h.api.emit('search_used',{});await h.api.flush();await h.api.flush();
    assert.equal(h.requests.length,2);assert.equal(JSON.parse(h.requests[0].options.body).events[0].id,JSON.parse(h.requests[1].options.body).events[0].id);
  }
});
