const {test}=require('node:test');const assert=require('node:assert/strict');const S=require('../../netlify/functions/lib/analytics-service.cjs');const C=require('../../netlify/functions/lib/analytics-core.cjs');
const now=Date.UTC(2026,8,5),job={link:'https://job-boards.greenhouse.io/acme/jobs/12345',ind:'Social',role:'Social Media',pay:'$80K-90K'},jobId=C.jobId(job);
const {database}=require('./helpers/analytics-store.cjs');
function deps(){return {env:{SU_ALLOWED_ORIGINS:'http://localhost:8013',SU_ANALYTICS_SECRET:'synthetic-test-only-secret',SU_ANALYTICS_ADMIN_UIDS:'owner'},db:database(),jobs:C.catalog([job]),now:()=>now,auth:{verifyIdToken:async(token,check)=>{assert.equal(check,true);if(!['alice','bob','owner'].includes(token))throw Error('invalid');return {uid:token};},getUser:async()=>({metadata:{creationTime:new Date(now-1000).toISOString()}})}};}
function request(token='alice',events=[{name:'job_open',jobId}],extra={}){return {httpMethod:'POST',headers:{origin:'http://localhost:8013',authorization:'Bearer '+token},body:JSON.stringify({session:'session1234567890',visitor:'visitor1234567890',consent:{analytics:true,personalization:true},events:events.map((e,i)=>({id:'testevent123456789'+i,page:'board',occurredAt:now,...e})),...extra})};}
test('collector verifies token, derives account from token and deduplicates retries',async()=>{const d=deps(),r=request();assert.equal((await S.collect(r,d)).accepted,1);assert.equal((await S.collect(r,d)).accepted,0);const profile=await S.profile({...r,httpMethod:'GET'},d);assert.equal(profile.jobs[jobId].weight,1);const other=await S.profile({...request('bob'),httpMethod:'GET'},d);assert.deepEqual(other.jobs,{});});
test('invalid tokens, cross-origin, missing consent and forged unknown jobs fail closed',async()=>{const d=deps();await assert.rejects(()=>S.collect(request('forged'),d),e=>e.status===401);const r=request();r.headers.origin='https://evil.example';await assert.rejects(()=>S.collect(r,d),e=>e.status===403);await assert.rejects(()=>S.collect(request('alice',undefined,{consent:{}}),d),e=>e.status===403);await assert.rejects(()=>S.collect(request('alice',[{name:'job_open',jobId:'f'.repeat(64)}]),d),e=>e.status===400);assert.equal(d.db.data.size,0);});
test('PII and client-supplied fields are excluded and employer metadata is trusted',async()=>{const d=deps();await S.collect(request('alice',[{name:'job_open',jobId,email:'secret@example.invalid',notes:'private',url:'https://secret',field:'Fake',uid:'bob'}]),d);const text=JSON.stringify([...d.db.data]);assert.doesNotMatch(text,/secret|private|Fake|"bob"/);assert.match(text,/Marketing/);});
test('personalization-only produces a profile without owner-report behavior',async()=>{const d=deps();await S.collect(request('alice',undefined,{consent:{analytics:false,personalization:true}}),d);const admin=await S.admin({...request('owner'),httpMethod:'GET'},d);assert.equal(admin.totals.events,0);assert.equal((await S.profile({...request(),httpMethod:'GET'},d)).jobs[jobId].weight,1);});
test('owner allowlist is server-enforced and query excludes other private metadata',async()=>{const d=deps();await S.collect(request(),d);await assert.rejects(()=>S.admin({...request('alice'),httpMethod:'GET'},d),e=>e.status===403);const out=await S.admin({...request('owner'),httpMethod:'GET'},d);assert.equal(out.totals.job_opens,1);assert.deepEqual(out.fields,[]);assert.doesNotMatch(JSON.stringify(out),/alice|visitor123|session123|testevent/);});
test('signup counts require verified Auth creation and ignores browser-declared signup',async()=>{const d=deps();await S.collect(request('alice',[{name:'auth_signup'},{name:'auth_login'}]),d);const out=await S.admin({...request('owner'),httpMethod:'GET'},d);assert.equal(out.totals.signups,1);assert.equal(out.totals.logins,1);});
test('reset clears profile and raw data, preserves other tenant and blocks queued older event',async()=>{const d=deps();await S.collect(request(),d);await S.collect(request('bob'),d);const out=await S.profile({...request(),httpMethod:'DELETE'},d);assert.equal(out.reset,true);assert.deepEqual((await S.profile({...request(),httpMethod:'GET'},d)).jobs,{});assert.equal((await S.profile({...request('bob'),httpMethod:'GET'},d)).jobs[jobId].weight,1);assert.equal((await S.collect(request('alice',[{name:'job_save',jobId,id:'newreceipt12345678'}]),d)).accepted,0);});
test('scheduled cleanup deletes expired analytics only',async()=>{const d=deps();d.db.data.set('suAnalyticsEvents/old',{expiresAt:new Date(now-1)});d.db.data.set('suAnalyticsEvents/current',{expiresAt:new Date(now+1)});d.db.data.set('users/alice',{notes:'private'});assert.equal((await S.cleanup(d)).deleted,1);assert.equal(d.db.data.has('users/alice'),true);assert.equal(d.db.data.has('suAnalyticsEvents/current'),true);});
test('outbound unknown intervals never become zero or completed applications',()=>{const base={actor:'a',session:'s',at:now,analytics:true};const out=C.reduceRows([{...base,name:'outbound_started',outboundId:'x'},{...base,name:'outbound_started',outboundId:'y'},{...base,name:'outbound_return',outboundId:'y',seconds:900,capped:true},{...base,at:now-31*86400000,name:'page_view'}],30,now);assert.equal(out.totals.events,3);assert.deepEqual(out.timing,{returned:1,unknown:1,capped:1,meanAwaySeconds:900});assert.equal(out.totals.reported_applied,0);});
test('same-origin browser GET without Origin accepted; foreign site denied',()=>{assert.doesNotThrow(()=>C.authorizeOrigin({httpMethod:'GET',headers:{host:'localhost:8013','sec-fetch-site':'same-origin'}},{SU_ALLOWED_ORIGINS:'http://localhost:8013'}));assert.throws(()=>C.authorizeOrigin({httpMethod:'GET',headers:{host:'localhost:8013','sec-fetch-site':'cross-site'}},{SU_ALLOWED_ORIGINS:'http://localhost:8013'}));});
module.exports={database,deps,request,jobId,now};

test('signal expiry survives unrelatedday89activity and keepsnewersignals duringday91cleanup',async()=>{
 const d=deps();let time=now;d.now=()=>time;
 await S.collect(request(),d);
 const newer={...job,link:'https://job-boards.greenhouse.io/acme/jobs/23456'},newId=C.jobId(newer);d.jobs={...d.jobs,...C.catalog([newer])};
 time=now+50*86400000;await S.collect(request('alice',[{id:'newer-event-123456',name:'job_open',jobId:newId,occurredAt:time}]),d);
 time=now+89*86400000;await S.collect(request('alice',[{id:'pageview-event-123456',name:'page_view',occurredAt:time}],{consent:{analytics:true,personalization:false}}),d);
 const actor=S.hmac(d.env,'account:alice'),ref='suAnalyticsProfiles/'+actor;
 assert.equal(+d.db.data.get(ref).expiresAt,now+179*86400000);assert.equal(+d.db.data.get(ref).nextSignalExpiryAt,now+90*86400000);
 time=now+91*86400000;const result=await S.cleanup(d);assert.equal(result.pruned,1);
 const retained=d.db.data.get(ref);assert.equal(retained.jobs[jobId],undefined);assert.equal(retained.jobs[newId].at,now+50*86400000);assert.equal(+retained.nextSignalExpiryAt,now+140*86400000);
});
