'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),vm=require('node:vm');
const Queue=require('../../netlify/functions/lib/report-queue-core.cjs'),Core=require('../../netlify/functions/lib/job-moderation-core.cjs'),Identity=require('../../js/job-identity.js'),Availability=require('../../netlify/functions/lib/job-availability-core.cjs'),Outbox=require('../../netlify/functions/lib/availability-outbox.cjs');
const modules=Promise.all([import('../../netlify/functions/lib/availability-verifier.mjs'),import('../../netlify/functions/lib/availability-worker.mjs'),import('../../netlify/functions/lib/availability-alert-delivery.mjs')]);
const NOW=1789300000000,link='https://job-boards.greenhouse.io/example/jobs/1234',ctx={site:{id:Core.SITE_ID,name:'stillunemployed'},deploy:{context:'branch-deploy'}};
function storage(initial){const data=new Map(initial?[['state',JSON.stringify(initial)]]:[]);let etag=1;return {writes:0,data,async getWithMetadata(key){return data.has(key)?{data:data.get(key),etag:String(etag)}:null;},async setJSON(key,value,condition){if(condition&&(condition.onlyIfNew?data.has(key):condition.onlyIfMatch!==String(etag)))return {modified:false};data.set(key,JSON.stringify(value));etag++;this.writes++;return {modified:true};}};}
function state({signed=true,status=signed?'quarantined':'queued_check',human=false}={}){const s=Queue.empty();s.records.push({reportId:'a'.repeat(64),link,keys:Identity.keys(link),slugs:['example-1234'],receivedAt:new Date(NOW-1000).toISOString(),status,revision:1,reporters:signed?['account:member']:[],reviews:[],needsCheck:true,humanReviewRequired:human,metadata:{co:'Example',role:'Designer'}});return s;}
const response=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}});
test('ATS target construction accepts supported exact identities and cannot turn a report into arbitrary network access',async()=>{const [V]=await modules;assert.equal(V.targetFor(link).url,'https://boards-api.greenhouse.io/v1/boards/example/jobs/1234');for(const value of ['https://127.0.0.1/job','https://example.com/jobs/123','https://job-boards.greenhouse.io.evil.example/example/jobs/1234','https://job-boards.greenhouse.io/example/jobs/1234?gh_jid=999','https://evil@jobs.lever.co/a/11111111-2222-3333-4444-555555555555'])assert.equal(V.targetFor(value),null);const target=V.targetFor('https://company.wd5.myworkdayjobs.com/en-US/Careers/job/NY/Designer_R1234');assert.equal(target.url,'https://company.wd5.myworkdayjobs.com/wday/cxs/company/Careers/job/NY/Designer_R1234');let fetched=0;const unknown=await V.verifyPosting('https://example.com/jobs/1',{fetchImpl:()=>fetched++,now:()=>NOW});assert.equal(unknown.result,'unknown');assert.equal(fetched,0);});
test('Greenhouse exact current published ID is open, mismatches and expired deadlines are unknown',async()=>{const [V]=await modules;for(const [body,result] of [[{id:1234,title:'Designer',content:'Work with our design team'},'open'],[{id:5678,title:'Designer',content:'Work with our team'},'unknown'],[{id:1234,title:'Designer',content:'Work with our team',application_deadline:'2020-01-01'},'unknown']]){const r=await V.verifyPosting(link,{fetchImpl:async(url,o)=>{assert.equal(o.method,'GET');assert.equal(o.redirect,'manual');assert.equal(o.credentials,'omit');return response(body);},now:()=>NOW});assert.equal(r.result,result);}});
test('closure requires two exact Job not found bodies; bare404 and redirects are UNKNOWN',async()=>{const [V]=await modules;let count=0;const closed=await V.verifyPosting(link,{fetchImpl:async()=>{count++;return response({error:'Job not found'},404);},now:()=>NOW});assert.equal(count,2);assert.equal(closed.result,'closed');assert.equal(closed.evidence.checks,2);for(const r of [response({error:'Not found'},404),new Response('Gone',{status:404}),new Response('',{status:302,headers:{location:'https://169.254.169.254/'}}),new Response('x'.repeat(1048577),{headers:{'Content-Type':'application/json'}})]){const seen=[];const out=await V.verifyPosting(link,{fetchImpl:async url=>{seen.push(url);return r;},now:()=>NOW});assert.equal(out.result,'unknown');assert.equal(seen.length,1);}});
test('Workday explicit unavailable is closed; a timeout is never closure',async()=>{const [V]=await modules,wd='https://company.wd5.myworkdayjobs.com/en-US/Careers/job/NY/Designer_R1234';assert.equal((await V.verifyPosting(wd,{fetchImpl:async()=>response({postingAvailable:false}),now:()=>NOW})).result,'closed');assert.equal((await V.verifyPosting(wd,{fetchImpl:async()=>{throw Error('network private data');},now:()=>NOW})).result,'unknown');assert.equal((await V.verifyPosting(wd,{fetchImpl:async()=>response({postingAvailable:true,jobPostingInfo:{jobReqId:'R1234',title:'Designer',jobDescription:'Work with our design team'}}),now:()=>NOW})).result,'open');});
test('Ashby list membership alone is insufficient and missing membership is not closure',async()=>{const [V]=await modules,ashby='https://jobs.ashbyhq.com/example/11111111-2222-3333-4444-555555555555';for(const [jobs,result] of [[[],'unknown'],[[{jobUrl:ashby,title:'Designer',descriptionPlain:'Creative work',isListed:false,applyUrl:ashby+'/application'}],'unknown'],[[{jobUrl:ashby,title:'Designer',descriptionPlain:'Creative work',isListed:true,applyUrl:ashby+'/application'}],'open']])assert.equal((await V.verifyPosting(ashby,{fetchImpl:async()=>response({apiVersion:'1',jobs}),now:()=>NOW})).result,result);});
function observation(result){return {result,evidence:{url:link,sourceUrl:'https://boards-api.greenhouse.io/v1/boards/example/jobs/1234',type:result==='unknown'?'unknown':'explicit_'+result,excerpt:'Fixture authoritative evidence',checkedAt:new Date(NOW).toISOString(),checks:1}};}
test('worker records durable exact evidence and restores or retires one pending role per run',async()=>{const [,W]=await modules;for(const result of ['open','closed']){const s=state(),store=storage(s);const run=W.createWorker({openStore:()=>store,env:{SU_AVAILABILITY_CHECKS_ENABLED:'true'},verify:async()=>observation(result),now:()=>NOW});const receipt=await run(ctx),saved=JSON.parse(store.data.get('state'));assert.equal(receipt.outcome,result);assert.equal(saved.records[0].status,result==='open'?'restored':'retired');assert.equal(saved.records[0].reviews[0].actor,'scheduled-verifier');assert.equal(saved.records[0].needsCheck,false);assert.equal(JSON.parse(store.data.get('last-check-run')).runId,receipt.runId);assert.equal(Availability.publicIndex(saved).removed.length,result==='open'?0:1);}});
test('UNKNOWN produces a durable private alert; anonymous UNKNOWN does not quarantine',async()=>{const [,W]=await modules;for(const signed of [true,false]){const store=storage(state({signed}));const run=W.createWorker({openStore:()=>store,env:{SU_AVAILABILITY_CHECKS_ENABLED:'true'},verify:async()=>observation('unknown'),now:()=>NOW});await run(ctx);const saved=JSON.parse(store.data.get('state'));assert.equal(saved.records[0].status,'human_review');assert.equal(saved.records[0].outbox[0].status,'pending');assert.equal(saved.records[0].outbox[0].reason,'unknown_evidence');assert.equal(Availability.publicIndex(saved).removed.length,signed?1:0);}});
test('worker never rechecks a contradictory report already requiring a human, and disabled runs do no writes',async()=>{const [,W]=await modules;for(const enabled of [false,true]){const store=storage(state({human:true}));let calls=0;const run=W.createWorker({openStore:()=>store,env:{SU_AVAILABILITY_CHECKS_ENABLED:String(enabled)},verify:async()=>{calls++;},now:()=>NOW});const r=await run(ctx);assert.equal(calls,0);assert.equal(r.state,enabled?'completed':'disabled');if(!enabled)assert.equal(store.writes,0);}});
test('a concurrent owner review wins over an obsolete verifier observation',async()=>{const [,W]=await modules,store=storage(state());const run=W.createWorker({openStore:()=>store,env:{SU_AVAILABILITY_CHECKS_ENABLED:'true'},verify:async()=>{const s=JSON.parse(store.data.get('state'));s.records[0].revision=2;s.records[0].humanReviewRequired=true;await store.setJSON('state',s);return observation('closed');},now:()=>NOW});const r=await run(ctx);assert.equal(r.state,'superseded');assert.equal(JSON.parse(store.data.get('state')).records[0].status,'quarantined');});
const secret='synthetic-secret-for-test-not-a-real-key-123',env={SU_AVAILABILITY_ALERTS_ENABLED:'true',SU_AVAILABILITY_ALERT_URL:'https://script.google.com/macros/s/synthetic/exec',SU_AVAILABILITY_ALERT_SECRET:secret};
function alertState(){const s=state({human:true});Outbox.ensureAlert(s.records[0],'unknown_evidence',NOW);return s;}
test('outbox excludes reporter identity, and provider absence leaves the pending alert intact',async()=>{const [,,A]=await modules,s=alertState(),store=storage(s);const payload=Outbox.payload(s.records[0],s.records[0].outbox[0],'preview');assert.doesNotMatch(JSON.stringify(payload),/account:|member|notes|status/);const run=A.createDelivery({openStore:()=>store,env:{},now:()=>NOW});assert.equal((await run(ctx)).state,'disabled');assert.equal(store.writes,0);});
test('outbox reserves before dispatch, retries failures with stable ID and records sender acceptance',async()=>{const [,,A]=await modules,store=storage(alertState()),ids=[];let fail=true;const run=A.createDelivery({openStore:()=>store,env,now:()=>NOW,send:async payload=>{ids.push(payload.alertId);assert.equal(JSON.parse(store.data.get('state')).records[0].outbox[0].status,'sending');if(fail){fail=false;throw Error('uncertain network');}return {schemaVersion:1,alertId:payload.alertId,scope:'preview',status:'accepted_by_sender',at:new Date(NOW).toISOString()};}});assert.equal((await run(ctx)).state,'retry');assert.equal(JSON.parse(store.data.get('state')).records[0].outbox[0].status,'pending');assert.equal((await run(ctx)).state,'accepted_by_sender');assert.equal(ids[0],ids[1]);assert.equal((await run(ctx)).state,'idle');assert.equal(ids.length,2);});
test('outbox holds an uncertain sender result for human reconciliation instead of resending',async()=>{const [,,A]=await modules,store=storage(alertState());let calls=0;const run=A.createDelivery({openStore:()=>store,env,now:()=>NOW,send:async payload=>{calls++;return {schemaVersion:1,alertId:payload.alertId,scope:'preview',status:'uncertain',at:new Date(NOW).toISOString()};}});assert.equal((await run(ctx)).state,'uncertain');assert.equal((await run(ctx)).state,'idle');assert.equal(calls,1);});
function receiver(){const properties=new Map([['SU_AVAILABILITY_ALERT_SECRET',secret]]),sent=[];let quota=1,throwSend=false;const runtime={PropertiesService:{getScriptProperties:()=>({getProperty:k=>properties.get(k),setProperty:(k,v)=>properties.set(k,v),getProperties:()=>Object.fromEntries(properties)})},Utilities:{Charset:{UTF_8:'utf8'},DigestAlgorithm:{SHA_256:'sha256'},computeHmacSha256Signature:(v,k)=>Array.from(crypto.createHmac('sha256',k).update(v).digest()),computeDigest:(a,v)=>Array.from(crypto.createHash('sha256').update(v).digest())},MailApp:{getRemainingDailyQuota:()=>quota,sendEmail:value=>{sent.push(value);if(throwSend)throw Error('ambiguous');}},LockService:{getScriptLock:()=>({tryLock:()=>true,releaseLock(){}})},ContentService:{MimeType:{JSON:'json'},createTextOutput:value=>({value,setMimeType(){return this;}})},Date:class extends Date{static now(){return NOW;}}};vm.createContext(runtime);vm.runInContext(fs.readFileSync('ops/availability-alerts/Code.gs','utf8'),runtime);return {properties,sent,setQuota:n=>quota=n,failSend:()=>throwSend=true,post:body=>JSON.parse(runtime.doPost({postData:{contents:body}}).value)};}
test('signed sender adapter and private receiver agree on receipts and never send twice after a retry',async()=>{const [,,A]=await modules,r=receiver(),s=alertState(),payload=Outbox.payload(s.records[0],s.records[0].outbox[0],'preview');const fetchImpl=async(url,o)=>response(r.post(o.body));const first=await A.sendAlert(payload,{config:A.configuration(env),fetchImpl,now:()=>NOW});assert.equal(first.status,'accepted_by_sender');await A.sendAlert(payload,{config:A.configuration(env),fetchImpl,now:()=>NOW});assert.equal(r.sent.length,1);assert.equal(r.sent[0].to,'NicholasdAlexis@gmail.com');assert.equal(r.post(JSON.stringify({...payload,sentAt:NOW,nonce:crypto.randomUUID(),signature:'a'.repeat(64)})).error,'Not authorized');assert.equal(r.sent.length,1);});
test('zero mail quota stays retryable and an ambiguous MailApp call is reserved without another send',async()=>{const [,,A]=await modules,r=receiver(),s=alertState(),payload=Outbox.payload(s.records[0],s.records[0].outbox[0],'preview'),options={config:A.configuration(env),fetchImpl:async(u,o)=>response(r.post(o.body)),now:()=>NOW};r.setQuota(0);assert.equal((await A.sendAlert(payload,options)).status,'retry');assert.equal(r.sent.length,0);r.setQuota(1);r.failSend();assert.equal((await A.sendAlert(payload,options)).status,'uncertain');assert.equal((await A.sendAlert(payload,options)).status,'uncertain');assert.equal(r.sent.length,1);});
test('alert adapter refuses forged acknowledgments and redirects outside the Google response host',async()=>{const [,,A]=await modules,s=alertState(),payload=Outbox.payload(s.records[0],s.records[0].outbox[0],'preview');for(const fetchImpl of [async()=>response({schemaVersion:1,alertId:payload.alertId,scope:'preview',status:'accepted_by_sender',at:new Date(NOW).toISOString(),signature:'a'.repeat(64)}),async()=>new Response('',{status:302,headers:{location:'https://evil.example/collect'}})])await assert.rejects(()=>A.sendAlert(payload,{config:A.configuration(env),fetchImpl,now:()=>NOW}));});
test('historical signed reporters cannot authorize an anonymous UNKNOWN hold after restoration',async()=>{
  const [,W]=await modules,S=await import('../../netlify/functions/lib/job-availability.mjs'),origin='https://preview--stillunemployed.netlify.app';
  for(const signed of [false,true]){
    const initial=state({status:'restored'});initial.records[0].needsCheck=false;initial.records[0].lastReviewedReporters=['account:member'];
    const store=storage(initial),service=S.createService({openStore:()=>store,authenticate:async()=>({uid:'member'}),getCatalog:async()=>({jobs:[{co:'Example',role:'Designer',link}],checkedAt:NOW}),now:()=>NOW});
    const request=new Request(origin+'/api/job-availability',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json',...(signed?{Authorization:'Bearer fixture'}:{})},body:JSON.stringify({requestId:crypto.randomUUID(),link})});
    const accepted=await service(request,{...ctx,ip:'203.0.113.10'});assert.equal(accepted.status,202);assert.equal((await accepted.json()).globallyHidden,false);
    const before=JSON.parse(store.data.get('state'));assert.equal(before.records[0].holdAuthorized,signed);
    await W.createWorker({openStore:()=>store,env:{SU_AVAILABILITY_CHECKS_ENABLED:'true'},verify:async()=>observation('unknown'),now:()=>NOW})(ctx);
    const after=JSON.parse(store.data.get('state'));assert.equal(after.records[0].status,'human_review');assert.equal(Availability.publicIndex(after).removed.length,signed?1:0);assert.equal(after.records[0].reporters.length,1);
  }
});
test('signed quota retries remain pending with backoff and recover after more than five attempts',async()=>{
  const [,,A]=await modules,store=storage(alertState());let at=NOW,calls=0;
  const run=A.createDelivery({openStore:()=>store,env,now:()=>at,send:async payload=>({schemaVersion:1,alertId:payload.alertId,scope:'preview',status:++calls<=7?'retry':'accepted_by_sender',at:new Date(at).toISOString()})});
  for(let i=0;i<7;i++){
    assert.equal((await run(ctx)).state,'retry');const a=JSON.parse(store.data.get('state')).records[0].outbox[0];assert.equal(a.status,'pending');assert.equal(a.ambiguousAttempts,0);assert.ok(Date.parse(a.nextAttemptAt)>at);assert.ok(Date.parse(a.nextAttemptAt)-at<=21600000);
    assert.equal((await run(ctx)).state,'idle');at=Date.parse(a.nextAttemptAt);
  }
  assert.equal((await run(ctx)).state,'accepted_by_sender');assert.equal(calls,8);
});
