'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
const Core=require('../../netlify/functions/lib/job-moderation-core.cjs'),Queue=require('../../netlify/functions/lib/report-queue-core.cjs');
const modules=Promise.all([import('../../netlify/functions/lib/tracker-reports.mjs'),import('../../netlify/functions/lib/job-availability.mjs'),import('../../netlify/functions/lib/community-auth.mjs'),import('jose')]);
const NOW=1789300000000,ORIGIN='https://preview--stillunemployed.netlify.app';
const ctx={site:{id:Core.SITE_ID,name:'stillunemployed'},deploy:{context:'branch-deploy'},ip:'203.0.113.10'};
const jobs=[1,2,3,4,5,6].map(n=>({co:'Company '+n,role:'Designer',link:'https://example.com/jobs/'+n,aliases:['example-'+n],pay:'$50K'}));
const tracker=(extra={})=>({requestId:randomUUID(),job:{link:jobs[0].link,company:'Company 1',role:'Designer',source:'LinkedIn'},reason:'suspicious',...extra});
const availability=(extra={})=>({requestId:randomUUID(),link:jobs[0].link,...extra});
function storage(){let value=null,etag=0;return {writes:0,conflicts:0,get text(){return value;},set text(v){value=v;etag++;},async getWithMetadata(){return value===null?null:{data:value,etag:String(etag)};},async setJSON(k,v,o){assert.equal(k,'state');if(this.conflicts-->0)return {modified:false};if(o.onlyIfNew?value!==null:o.onlyIfMatch!==String(etag))return {modified:false};value=JSON.stringify(v);etag++;this.writes++;return {modified:true};}};}
function req(input,{method=input?'POST':'GET',headers={},origin=ORIGIN,query=''}={}){return new Request(origin+'/api/report'+query,{method,headers:{...(input?{'Content-Type':'application/json',Origin:origin}:{}),...headers},...(input?{body:JSON.stringify(input)}:{})});}
async function fixture(kind='tracker',options={}){const [Tracker,Availability]=await modules,store=storage(),seen=[];const handle=(kind==='tracker'?Tracker:Availability).createService({openStore:scope=>{seen.push(scope);return store;},authenticate:async r=>({uid:r.headers.get('x-test-user')||'synthetic-member'}),owner:async()=>({role:'owner'}),getCatalog:async()=>({jobs,checkedAt:NOW}),now:()=>NOW,...options});return {store,seen,async call(input,opts={},extra={},context=ctx){const r=await handle(req(input,opts),context,extra);return {status:r.status,body:await r.json(),headers:r.headers};}};}

test('tracker reports store only the public job snapshot and review reason, and stay private',async()=>{const f=await fixture(),input=tracker(),r=await f.call(input);assert.equal(r.status,202);assert.equal(r.body.status,'pending_review');assert.match(r.body.reportId,/^[a-f0-9]{64}$/);assert.equal(r.body.globallyHidden,undefined);const stored=JSON.parse(f.store.text);assert.deepEqual(stored.records[0].job,input.job);assert.equal(stored.records[0].actor,'account:synthetic-member');const read=await f.call();assert.equal(read.body.records.length,1);assert.equal(read.body.secret,undefined);assert.equal(read.body.receipts,undefined);assert.equal(read.headers.get('cache-control'),'no-store');assert.equal(read.headers.get('access-control-allow-origin'),null);});
test('external rows permit optional link and either company or role, never require synthetic placeholders',async()=>{const f=await fixture();for(const job of [{link:'',company:'A',role:'',source:'Other'},{link:'',company:'',role:'Writer',source:'Referral'}])assert.equal((await f.call(tracker({job}))).status,202);assert.equal((await f.call(tracker({job:{link:'',company:'',role:'',source:'Other'}}))).status,400);});
test('public Greenhouse posting tokens are admitted narrowly and distinct fragment job routes are preserved',async()=>{const link='https://boards.greenhouse.io/embed/job_app?for=glossier&token=8054875';assert.equal(Queue.publicURL(link),link);for(const unsafe of [link.replace('8054875','private-auth-token'),link.replace('boards.greenhouse.io','example.com'),link+'&token=8054876',link+'&access_token=private','https://example.com/job#access_token=private'])assert.throws(()=>Queue.publicURL(unsafe));const routed=jobs[0].link+'#/jobs/another';assert.equal(Queue.publicURL(routed),routed);const f=await fixture('availability');assert.equal((await f.call(availability({link:routed}),{headers:{Authorization:'Bearer synthetic'}})).status,409);assert.equal(f.store.writes,0);});
test('private fields, unknown schema, dangerous URLs and malformed reasons are rejected without writes',async()=>{for(const input of [tracker({notes:'private'}),tracker({reason:'remove'}),tracker({job:{...tracker().job,notes:'private'}}),tracker({job:{...tracker().job,source:'Other platform'}}),...['file:///etc/passwd','javascript:alert(1)','https://127.0.0.1/job','https://[::1]/job','https://localhost/job','https://service.local/job','https://user:pass@example.com/job','https://example.com:8080/job','https://example.com/job?access_token=private'].map(link=>tracker({job:{...tracker().job,link}}))]){const f=await fixture();assert.equal((await f.call(input)).status,400);assert.equal(f.store.writes,0);}});
test('reports require same-origin JSON and current account, queue read requires owner',async()=>{const f=await fixture();assert.equal((await f.call(tracker(),{headers:{Origin:'https://evil.example'}})).status,403);assert.equal((await f.call(tracker(),{headers:{'Sec-Fetch-Site':'cross-site'}})).status,403);assert.equal((await f.call(tracker(),{headers:{'Content-Type':'text/plain'}})).status,415);const g=await fixture('tracker',{authenticate:async()=>{throw Core.fail(401,'Sign in');},owner:async()=>{throw Core.fail(403,'Owner required');}});assert.equal((await g.call(tracker())).status,401);assert.equal((await g.call()).status,403);assert.equal(g.seen.length,0);});
test('same request recovers idempotently; new duplicate preserves one record; reused payload ID conflicts',async()=>{const f=await fixture(),input=tracker(),one=await f.call(input),two=await f.call(input);assert.equal(two.body.reportId,one.body.reportId);assert.equal(two.body.duplicate,true);assert.equal(f.store.writes,1);assert.equal((await f.call({...input,reason:'other'})).status,409);const duplicate=await f.call({...input,requestId:randomUUID()});assert.equal(duplicate.body.reportId,one.body.reportId);assert.equal(duplicate.body.duplicate,true);assert.equal(JSON.parse(f.store.text).records.length,1);});
test('rate caps and CAS preserve concurrent reports without overwriting another account',async()=>{const f=await fixture();const input=tracker();const r=await Promise.all([f.call(input),f.call(tracker({reason:'other'}))]);assert.ok(r.every(x=>x.status===202));for(let i=0;i<3;i++)assert.equal((await f.call(tracker())).status,202);assert.equal((await f.call(tracker())).status,429);assert.equal(JSON.parse(f.store.text).receipts.length,5);const g=await fixture();g.store.conflicts=4;assert.equal((await g.call(tracker())).status,409);assert.equal(g.store.writes,0);});
test('corrupt storage and ambiguous readback return errors, never false received success',async()=>{const f=await fixture();f.store.text='{}';assert.equal((await f.call(tracker())).status,503);const g=await fixture(),input=tracker(),read=g.store.getWithMetadata.bind(g.store);let fail=true;g.store.getWithMetadata=async()=>{if(g.store.writes&&fail){fail=false;throw Error('secret upstream text');}return read();};assert.equal((await g.call(input)).status,503);assert.equal((await g.call(input)).status,202);assert.equal(g.store.writes,1);});
test('preview and production stores follow trusted deployment metadata, never client scope',async()=>{const f=await fixture();assert.equal((await f.call(tracker(),{origin:'https://stillunemployed.com'},{},{...ctx,deploy:{context:'production'}})).status,202);assert.deepEqual(f.seen,['production']);assert.equal((await f.call(tracker({scope:'production'}))).status,400);});

test('signed-out availability is queued only; a verified account quarantines current canonical role',async()=>{const f=await fixture('availability'),anon=await f.call(availability());assert.equal(anon.body.status,'queued_check');assert.equal(anon.body.globallyHidden,false);assert.equal((await f.call()).body.removed.length,0);const signed=await f.call(availability(),{headers:{Authorization:'Bearer synthetic'}});assert.equal(signed.body.status,'quarantined');assert.equal(signed.body.globallyHidden,true);const index=await f.call();assert.equal(index.body.removed.length,1);assert.deepEqual(Object.keys(index.body.removed[0]).sort(),['keys','link','slugs']);assert.ok(!JSON.stringify(index.body).includes('synthetic-member'));});
test('invalid sign-in does not silently downgrade into anonymous queue; unknown catalog does not mutate',async()=>{const f=await fixture('availability',{authenticate:async()=>{throw Core.fail(401,'Sign in');}});assert.equal((await f.call(availability(),{headers:{Authorization:'Bearer invalid'}})).status,401);assert.equal(f.store.writes,0);for(const catalog of [{jobs:[],checkedAt:NOW},{jobs:[jobs[0],jobs[0]],checkedAt:NOW},{jobs,checkedAt:NOW-31000}]){const g=await fixture('availability',{getCatalog:async()=>catalog});assert.ok([409,503].includes((await g.call(availability())).status));assert.equal(g.store.writes,0);}});
function review(result,expectedRevision,type,excerpt){return availability({result,expectedRevision,evidence:{url:jobs[0].link,type,excerpt,checkedAt:new Date(NOW).toISOString()}});}
test('verified open restores; independent report after restoration escalates instead of repeating auto-verification',async()=>{const f=await fixture('availability');const member={headers:{Authorization:'Bearer synthetic'}};await f.call(availability(),member);let r=await f.call(review('open',1,'explicit_open','Apply for this role'),{}, {review:true});assert.equal(r.body.status,'restored');assert.equal((await f.call()).body.removed.length,0);r=await f.call(availability(),member);assert.equal(r.body.status,'restored');r=await f.call(availability(),{headers:{Authorization:'Bearer synthetic','x-test-user':'independent-member'}});assert.equal(r.body.status,'human_review');assert.equal(r.body.globallyHidden,true);});
test('UNKNOWN remains undecided, stale revisions and weak closed evidence cannot retire a role',async()=>{const f=await fixture('availability');await f.call(availability(),{headers:{Authorization:'Bearer synthetic'}});assert.equal((await f.call(review('closed',1,'explicit_closed','HTTP 404'),{},{review:true})).status,400);assert.equal((await f.call(review('closed',0,'job_not_found','Job not found'),{},{review:true})).status,400);assert.equal((await f.call(review('closed',1,'workday_unavailable','postingAvailable: false'),{},{review:true})).body.status,'retired');assert.equal((await f.call(review('open',1,'explicit_open','Apply now'),{},{review:true})).status,409);const g=await fixture('availability');await g.call(availability());const unknown=await g.call(review('unknown',1,'unknown','Blocked by CAPTCHA'),{},{review:true});assert.equal(unknown.body.status,'human_review');assert.equal(unknown.body.globallyHidden,false);});
test('availability queue and owner actions remain private and fail closed without owner authorization',async()=>{const f=await fixture('availability',{owner:async()=>{throw Core.fail(403,'Owner required');}});assert.equal((await f.call(null,{},{admin:true})).status,403);assert.equal((await f.call(review('closed',1,'job_not_found','Job not found'),{},{review:true})).status,403);assert.equal(f.seen.length,0);});

test('community auth verifies RS256 claims and a current enabled Google account without granting owner access',async()=>{const [,,Auth,jose]=await modules,{privateKey,publicKey}=await jose.generateKeyPair('RS256');const t=Math.floor(NOW/1000),payload={sub:'ordinary-member',email:'member@example.com',email_verified:true,auth_time:t-10,firebase:{sign_in_provider:'google.com'}};const token=await new jose.SignJWT(payload).setProtectedHeader({alg:'RS256',kid:'fixture'}).setAudience('stillunemployed-17de9').setIssuer('https://securetoken.google.com/stillunemployed-17de9').setIssuedAt(t-5).setExpirationTime(t+100).sign(privateKey);const account={localId:payload.sub,email:payload.email,emailVerified:true,validSince:String(t-20),providerUserInfo:[{providerId:'google.com'}]};const verified=await Auth.verifyCommunity(req(tracker(),{headers:{Authorization:'Bearer '+token}}),{keySet:publicKey,now:()=>NOW,fetchImpl:async()=>new Response(JSON.stringify({users:[account]}),{headers:{'Content-Type':'application/json'}})});assert.deepEqual(verified,{uid:'ordinary-member'});for(const extra of [{disabled:true},{emailVerified:false},{localId:'other'},{validSince:String(t)},{providerUserInfo:[]}])assert.throws(()=>Auth.validateAccount(payload,{users:[{...account,...extra}]}));const claims={...payload,aud:'stillunemployed-17de9',iss:'https://securetoken.google.com/stillunemployed-17de9',iat:t,exp:t+100};for(const extra of [{email_verified:false},{firebase:{sign_in_provider:'password'}},{firebase:{sign_in_provider:'google.com',tenant:'other'}},{aud:'other'},{auth_time:t+1}])assert.throws(()=>Auth.validateClaims({...claims,...extra},NOW));});
