const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
const source=fs.readFileSync(require.resolve('../../js/newsletter-attribution.js'),'utf8');
const BASE='https://subscribe-forms.beehiiv.com/af2e314d-125f-431d-a8e0-0020be04d97c';
const turn=()=>new Promise(resolve=>setImmediate(resolve));
function harness({consent=true,excluded=false,mode='ok'}={}){
 const storage={},events=[],requests=[],issued=[],listeners={},observers=[],timers=[];let activeConsent=consent;
 const doc={hidden:false,activeElement:null};
 const win={crypto:crypto.webcrypto,SUAnalytics:{choices:()=>({analytics:activeConsent}),excluded:()=>excluded,emit:(name,params)=>events.push({name,...params}),newsletterRequest:async(token,context,signal)=>{issued.push({token,context});if(mode==='fail')throw Error('offline');if(mode==='timeout')return new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(Error('timeout'))));return {campaign:'su_'+token,jobId:context.link?'b'.repeat(64):undefined};}},addEventListener:(n,f)=>{listeners[n]=f;}};
 class Observer{constructor(callback){this.callback=callback;observers.push(this);}observe(frame){this.frame=frame;}disconnect(){this.disconnected=true;}}
 win.IntersectionObserver=Observer;
 vm.runInNewContext(source,{window:win,document:doc,URL,Uint8Array,AbortController,IntersectionObserver:Observer,localStorage:{getItem:k=>storage[k]||null,setItem:(k,v)=>{storage[k]=v;},removeItem:k=>{delete storage[k];}},setTimeout:(fn,ms)=>{timers.push({fn,ms});return timers.length;},clearTimeout:()=>{},fetch:async(url,options)=>{requests.push({url,body:JSON.parse(options.body)});return {ok:true};}});
 return {win,doc,storage,events,requests,issued,observers,timers,load:(frame,context={placement:'advice',cta:'N01',exposure:1})=>win.SUNewsletter.load(frame,BASE,context),consent:value=>{activeConsent=value;listeners['su:consent-changed']();},auth:()=>listeners['su:auth-changed']({detail:{accountChanged:true}}),blur:frame=>{doc.activeElement=frame;listeners.blur();timers.filter(t=>t.ms===0).forEach(t=>t.fn());}};
}
test('denied, QA and excluded browsing load the original form with no attribution requests or IDs',async()=>{for(const opts of [{consent:false},{excluded:true}]){const h=harness(opts),frame={isConnected:true};h.load(frame);await turn();assert.equal(frame.src,BASE);assert.equal(h.issued.length,0);assert.deepEqual(h.storage,{});assert.deepEqual(h.events,[]);}});
test('tracked form carries only source and opaque receipt, counts actual visible exposure and focus separately',async()=>{const h=harness(),frame={isConnected:true};h.load(frame,{placement:'job-detail',cta:'N16',link:'https://example.invalid/job',exposure:1});await turn();const url=new URL(frame.src);assert.equal(url.searchParams.get('utm_source'),'stillunemployed');assert.match(url.searchParams.get('utm_campaign'),/^su_[a-f0-9]{64}$/);assert.doesNotMatch(frame.src,/example.invalid|N16|email/);assert.equal(h.events.length,0);h.observers[0].callback([{isIntersecting:true,intersectionRatio:0.49}]);assert.equal(h.events.length,0);h.observers[0].callback([{isIntersecting:true,intersectionRatio:0.8}]);h.blur(frame);h.blur(frame);assert.deepEqual(h.events.map(e=>e.name),['newsletter_impression','newsletter_engagement']);assert.equal(h.events[0].cta,'N16');assert.equal(h.events[0].revision,2);assert.equal(h.events.some(e=>e.name==='newsletter_confirmed'),false);});
test('rerenders and retries reuse one receipt and do not add duplicate visible exposures',async()=>{const h=harness(),frame={isConnected:true};h.load(frame);await turn();h.observers[0].callback([{isIntersecting:true,intersectionRatio:1}]);const next={isConnected:true};h.load(next);await turn();assert.equal(h.issued.length,1);assert.equal(frame.src,next.src);assert.equal(h.events.length,1);});
test('measurement failure and timeout still load a functioning plain form',async()=>{for(const mode of ['fail','timeout']){const h=harness({mode}),frame={isConnected:true};h.load(frame);if(mode==='timeout')h.timers.find(t=>t.ms===1200).fn();await turn();assert.equal(frame.src,BASE);assert.equal(h.events.length,0);}});
test('withdrawal revokes existing receipts; opting back in cannot attribute focus on an old form',async()=>{const h=harness(),frame={isConnected:true};h.load(frame);await turn();h.consent(false);await turn();assert.equal(h.requests[0].body.action,'revoke');assert.equal(h.requests[0].body.tokens.length,1);assert.deepEqual(h.storage,{});h.consent(true);h.blur(frame);assert.equal(h.events.length,0);});
test('account change revokes issued context and in-flight load cannot keep attribution',async()=>{const h=harness(),frame={isConnected:true};h.load(frame);h.auth();await turn();assert.equal(frame.src,BASE);assert.equal(h.events.length,0);assert.ok(h.requests.some(r=>r.body.action==='revoke'));});
test('detached form does not start a provider request',async()=>{const h=harness(),frame={isConnected:false};h.load(frame);await turn();assert.equal(frame.src,undefined);});
