const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const N=require('../../netlify/functions/lib/newsletter-attribution.cjs'),S=require('../../netlify/functions/lib/analytics-service.cjs'),C=require('../../netlify/functions/lib/analytics-core.cjs');
const {database}=require('./helpers/analytics-store.cjs');
const now=Date.UTC(2026,8,20),secret='whsec_'+Buffer.from('synthetic webhook test key only').toString('base64'),token='a'.repeat(64);
const job={link:'https://example.invalid/job/1',co:'Example',role:'Designer'},jobId=C.jobId(job);
function deps(){return {now:()=>now,db:database(),jobs:C.catalog([job]),env:{CONTEXT:'production',SU_ANALYTICS_ENABLED:'true',SU_NEWSLETTER_ATTRIBUTION_ENABLED:'true',SU_BEEHIIV_WEBHOOK_SECRET:secret,SU_ANALYTICS_SECRET:'test-key-only',SU_ALLOWED_ORIGINS:'https://stillunemployed.com',SU_ANALYTICS_ADMIN_UIDS:'owner'},auth:{verifyIdToken:async t=>{if(t==='invalid')throw Error();return {uid:t};}}};}
function request(extra={}){return {httpMethod:'POST',headers:{origin:'https://stillunemployed.com',authorization:'Bearer alice'},body:JSON.stringify({token,session:'session1234567890',visitor:'visitor1234567890',consent:{analytics:true},occurredAt:now,page:'board',placement:'job-detail',cta:'N16',jobId,...extra})};}
function hook(extra={},type='subscription.created',timestamp=now/1000){const body=JSON.stringify({event_type:type,event_timestamp:now/1000,data:{id:'sub_11111111-2222-3333-4444-555555555555',created:now/1000,status:'active',email:'private@example.invalid',utm_source:'stillunemployed',utm_medium:'website',utm_campaign:'su_'+token,...extra}});const headers={'svix-id':'msg_test_12345','svix-timestamp':String(timestamp)};headers['svix-signature']='v1,'+crypto.createHmac('sha256',Buffer.from(secret.slice(6),'base64')).update(headers['svix-id']+'.'+timestamp+'.'+body).digest('base64');return {body,headers};}
const rows=d=>[...d.db.data.values()].filter(r=>r.analytics===true);
test('official Svix published signature fixture verifies without a self-generated signature',()=>{const payload='{"event_type":"ping","data":{"success":true}}';assert.equal(N.verify(payload,{'svix-id':'msg_loFOjxBNrRLzqYUf','svix-timestamp':'1731705121','svix-signature':'v1,rAvfW3dJ/X/qxhsaXPOyyCGmRKsaKWcsNccKXlIktD0='},'whsec_plJ3nmyCDGBKInavdOK15jsl',1731705121000).event_type,'ping');});
test('reject signature tampering, stale/future timestamps, malformed JSON and oversized payload',()=>{for(const h of [ {...hook(),body:hook().body+' '},hook({},undefined,now/1000-301),hook({},undefined,now/1000+301),{...hook(),headers:{}}])assert.throws(()=>N.verify(h.body,h.headers,secret,now),e=>e.status===401);assert.throws(()=>N.verify('x'.repeat(65537),{},secret,now),e=>e.status===413);});
test('issued receipt stores only allowed public context and keyed actor',async()=>{const d=deps();assert.equal((await S.newsletter(request({email:'private@example.invalid',notes:'secret notes'}),d)).campaign,'su_'+token);const text=JSON.stringify([...d.db.data]);assert.doesNotMatch(text,/private@|secret notes|Bearer|alice|example.invalid/);assert.match(text,/Designer at Example/);assert.equal(rows(d).length,0);});
test('no consent, invalid identity, unknown job and arbitrary CTA are rejected',async()=>{for(const [extra,status] of [[{consent:{}},403],[{jobId:'b'.repeat(64)},400],[{cta:'private text'},400]]){const d=deps();await assert.rejects(S.newsletter(request(extra),d),e=>e.status===status);assert.equal(d.db.data.size,0);}const d=deps(),r=request();r.headers.authorization='Bearer invalid';await assert.rejects(S.newsletter(r,d),e=>e.status===401);});
test('preview, owner and disabled feature cannot issue an attribution code',async()=>{for(const scenario of ['preview','owner','off']){const d=deps(),r=request();if(scenario==='preview')d.env.CONTEXT='deploy-preview';if(scenario==='owner')r.headers.authorization='Bearer owner';if(scenario==='off'){d.env.SU_NEWSLETTER_ATTRIBUTION_ENABLED='false';await assert.rejects(S.newsletter(r,d),e=>e.status===503);}else assert.equal((await S.newsletter(r,d)).excluded,true);assert.equal(d.db.data.size,0);}});
test('pending creation is not a conversion; confirmation and retries count once',async()=>{const d=deps();await S.newsletter(request(),d);await N.receive(hook({status:'pending'}),d);assert.deepEqual(rows(d).map(r=>r.name),['newsletter_submitted']);await N.receive(hook({},'subscription.confirmed'),d);await N.receive(hook(),d);await N.receive(hook({},'subscription.confirmed'),d);assert.deepEqual(rows(d).map(r=>r.name).sort(),['newsletter_confirmed','newsletter_submitted']);assert.doesNotMatch(JSON.stringify([...d.db.data]),/private@|sub_111|msg_test/);});
test('active creation works when double opt-in is off, reordered confirmation does not duplicate',async()=>{const d=deps();await S.newsletter(request(),d);await N.receive(hook({},'subscription.confirmed'),d);await N.receive(hook(),d);assert.equal(rows(d).length,2);});
test('unknown receipt, unrelated source, unsupported events/status and expired receipts are ignored',async()=>{for(const extra of [{utm_campaign:'su_'+'b'.repeat(64)},{utm_source:'other'},{status:'inactive'}]){const d=deps();await S.newsletter(request(),d);assert.equal((await N.receive(hook(extra),d)).accepted,false);assert.equal(rows(d).length,0);}const d=deps();await S.newsletter(request(),d);assert.equal((await N.receive(hook({},'subscription.deleted'),d)).accepted,false);d.db.data.get('suAnalyticsEvents/newsletter-receipt-'+token).expiresAt=new Date(now-1);assert.equal((await N.receive(hook(),d)).accepted,false);});
test('withdrawal tombstone defeats an in-flight issue and future confirmation',async()=>{const d=deps();await S.newsletter(request({action:'revoke',tokens:[token]}),d);assert.equal((await S.newsletter(request(),d)).excluded,true);assert.equal((await N.receive(hook(),d)).accepted,false);assert.equal(rows(d).length,0);});
test('reset removes linked receipts and prevents conversion resurrection',async()=>{const d=deps();await S.newsletter(request(),d);await N.receive(hook(),d);await S.profile({...request(),httpMethod:'DELETE'},d);assert.equal(rows(d).length,0);assert.equal((await N.receive(hook(),d)).accepted,false);assert.equal((await S.newsletter(request(),d)).excluded,true);});
test('retention removes attribution receipts through the existing scheduled cleanup',async()=>{const d=deps();await S.newsletter(request(),d);d.db.data.get('suAnalyticsEvents/newsletter-receipt-'+token).expiresAt=new Date(now-1);await S.cleanup(d);assert.equal(d.db.data.has('suAnalyticsEvents/newsletter-receipt-'+token),false);});
test('browser cannot forge provider confirmation or submitted events',()=>{for(const name of ['newsletter_confirmed','newsletter_submitted'])assert.throws(()=>C.cleanEvent({name,id:'event123456789012',page:'board'},{}),e=>e.status===400);});
test('impression requires a receipt for the same actor/session, and provider context wins',async()=>{const d=deps();await S.newsletter(request(),d);const input={session:'session1234567890',visitor:'visitor1234567890',consent:{analytics:true},events:[{id:'event123456789012',name:'newsletter_impression',page:'board',occurredAt:now,placement:'job-detail',cta:'N01',jobId,newsletterReceipt:token}]};const r={...request(),body:JSON.stringify(input)};await S.collect(r,d);assert.equal(rows(d)[0].cta,'N16');assert.equal(rows(d)[0].exposureId,C.hash(token));const wrong={...r,headers:{...r.headers,authorization:'Bearer bob'}};assert.equal((await S.collect(wrong,d)).accepted,0);await N.receive(hook(),d);const report=N.aggregate(rows(d));assert.equal(report.impressions,1);assert.equal(report.rate,1);assert.deepEqual(report.cta,[]);});
test('cohort report deduplicates rerender exposures, only matches known impressions and suppresses small conversion groups',()=>{const events=[];for(let i=0;i<5;i++){const e={name:'newsletter_impression',exposureId:'e'+i,actor:'a'+i,cta:'N01',placement:'advice'};events.push(e,e);if(i<4)events.push({...e,name:'newsletter_confirmed'});}let report=N.aggregate(events);assert.equal(report.impressions,5);assert.equal(report.rate,0.8);assert.equal(report.cta[0].converted,null);events.push({...events[0],name:'newsletter_confirmed',exposureId:'unmatched'});report=N.aggregate(events);assert.equal(report.matchedConversions,4);});
test('existing subscribers cannot be counted as new acquisitions by a copied campaign',async()=>{const d=deps();await S.newsletter(request(),d);assert.equal((await N.receive(hook({created:now/1000-86400}),d)).accepted,false);assert.equal(rows(d).length,0);});
test('modern Netlify request boundary handles method, payload limits and sanitized failures',async()=>{const {respond}=await import('../../netlify/functions/_shared/newsletter-http.ts');global.Netlify={env:{get:()=>undefined}};try{const badMethod=await respond(new Request('https://example.invalid',{method:'GET'}),()=>{});assert.equal(badMethod.status,405);const large=await respond(new Request('https://example.invalid',{method:'POST',body:'x'.repeat(65537)}),()=>{});assert.equal(large.status,413);const good=await respond(new Request('https://example.invalid',{method:'POST',body:'{"safe":true}',headers:{'svix-id':'test'}}),(r)=>({raw:r.body,id:r.headers['svix-id']}),undefined,()=>({}));assert.deepEqual(await good.json(),{raw:'{"safe":true}',id:'test'});const failed=await respond(new Request('https://example.invalid',{method:'POST',body:'x'}),()=>{throw Error('private@example.invalid');},undefined,()=>({}));assert.equal(failed.status,503);assert.doesNotMatch(await failed.text(),/private/);}finally{delete global.Netlify;}});
