const {test}=require('node:test');const assert=require('node:assert/strict');const P=require('../../js/personalization.js');
const now=Date.UTC(2026,8,5);const job=(id,ind,pay='$70K-80K')=>({id,ind,pay,role:ind,link:'https://example.org/'+id});
function signals(marketing=8,fashion=1){let p={};for(let i=0;i<marketing;i++)p=P.update(p,{name:'job_open',jobId:'m'+i},{field:'Marketing',role:'Social Media'},now);for(let i=0;i<fashion;i++)p=P.update(p,{name:'job_open',jobId:'f'+i},{field:'Fashion Design',role:'Fashion Design'},now);return p;}
test('eight distinct marketing jobs strongly outweigh one fashion job',()=>{const jobs=Array.from({length:20},(_,i)=>job('m'+i,'Social')).concat(Array.from({length:20},(_,i)=>job('f'+i,'Fashion Design')));const top=P.rank(jobs,signals(),{now}).slice(0,9);assert.equal(top.filter(j=>j.ind==='Social').length,8);assert.equal(top.filter(j=>j.ind==='Fashion Design').length,1);});
test('equal interest naturally interleaves both fields',()=>{const jobs=Array.from({length:8},(_,i)=>job('m'+i,'Social')).concat(Array.from({length:8},(_,i)=>job('f'+i,'Fashion Design')));assert.deepEqual(P.rank(jobs,signals(5,5),{now}).slice(0,4).map(j=>j.ind),['Social','Fashion Design','Social','Fashion Design']);});
test('one job strongest action counts once and weak repeats do not refresh it',()=>{let p={};for(let i=0;i<20;i++)p=P.update(p,{name:'job_open',jobId:'same'},{field:'Fashion Design',role:'Fashion Design'},now+i);assert.equal(p.same.weight,1);assert.equal(p.same.at,now);p=P.update(p,{name:'job_save',jobId:'same'},{field:'Fashion Design',role:'Fashion Design'},now+10);p=P.update(p,{name:'apply_click',jobId:'same'},{field:'Fashion Design',role:'Fashion Design'},now+20);assert.equal(p.same.weight,4);assert.equal(Object.keys(p).length,1);});
test('higher salary does not outrank the existing variety inside a relevant role group',()=>{const jobs=[job('low','Fashion Design','$60K-100K'),job('high','Fashion Design','$80K-85K'),job('other','Social','$150K-200K')];assert.deepEqual(P.rank(jobs,signals(0,12),{now}).map(j=>j.id),['low','high','other']);});
test('hourly is never annualized or compared with annual slots',()=>{const jobs=[job('a','Social','$70K-85K'),job('h1','Social','$30-40/hr'),job('b','Social','$80K-90K'),job('h2','Social','$50-60/hr')];assert.deepEqual(P.rank(jobs,signals(),{now}).map(j=>j.id),['a','h1','b','h2']);assert.deepEqual(P.salary('$25-35/hr'),{basis:'hourly',minimum:25});});
test('Recently added is chronology with no high-pay override',()=>{const jobs=[{...job('high','Social','$150K-200K'),_idx:1},{...job('new','Fashion Design'),_idx:5}];assert.equal(P.rank(jobs,signals(),{now,recent:true})[0].id,'new');});
test('recency halves at30days and expires after90days; timing never contributes',()=>{const p={new:{field:'Marketing',role:'Social Media',weight:1,at:now},old:{field:'Fashion Design',role:'Fashion Design',weight:1,at:now-30*86400000},expired:{field:'Video',role:'Video',weight:5,at:now-91*86400000}};const v=P.preferences(p,now);assert.equal(v.fields.Marketing,1);assert.equal(v.fields['Fashion Design'],0.5);assert.equal(v.fields.Video,undefined);assert.deepEqual(P.update({}, {name:'outbound_return',jobId:'a'},{field:'Video'},now),{});});
test('away timing caps at900seconds, labels capped, and does not infer completion',()=>{assert.deepEqual(P.away(now,now+240000),{seconds:240,capped:false,returned:true});assert.deepEqual(P.away(now,now+1200000),{seconds:900,capped:true,returned:true});});
